spring:
  application:
    name: meet-friends
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meet_friends?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  session:
    timeout: 86400
    store-type: redis
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
# 配置日志
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭驼峰转换
    map-underscore-to-camel-case: false
    # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
knife4j:
  enable: true

# huawei ods
huawei:
  obs:
    ak: UZ8ZU5TAAPZLGW5IHL1A
    sk: cqrKbkpm3U4xULx3zessbcybyxGfkWPtJjcebn1w
    # 上传的endPoint
    upload:
      endPoint: obs.cn-south-1.myhuaweicloud.com
    # 访问的endPoint
    access:
      endPoint: obs.cn-south-1.myhuaweicloud.com
    # 桶
    bucketName: user-avatars
    urlPrefix: http://cdn.meetfei.cn/
baidu:
  ak: Xxt5idmN3iqhNP0dxuN22Z5KMoDnK1me
  url: http://api.map.baidu.com/geocoding/v3/?output=json&location=showLocation